platform :ios, '10.0'

inhibit_all_warnings!

use_frameworks!

target 'SmartHome' do
  pod 'Alamofire'
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'SVProgressHUD'
end

target 'SmartHomeTests' do
  pod 'Alamofire'
end
